using UnityEngine;

public class ParallaxEffect : MonoBehaviour
{
    public Transform cameraTransform; // C치mara principal
    public float parallaxFactor; // Velocidad del efecto (menor para el fondo m치s lejano)

    private Vector3 initialPosition;

    void Start()
    {
        // Guardar la posici칩n inicial
        initialPosition = transform.position;
    }

    void Update()
    {
        // Mover el fondo m치s lentamente dependiendo de su parallaxFactor
        Vector3 delta = cameraTransform.position * parallaxFactor;
        transform.position = new Vector3(initialPosition.x + delta.x, initialPosition.y, initialPosition.z);
    }
}
